---
ansible_user: root
ansible_ssh_private_key_file: ~/.ssh/id_ansible
physical_interface: ens224
portref: ansible_{{ physical_interface }}
prefix: 
  ipv4: 100.99.88.0/30
  ipv6: fdab:cdef:0123:4567:89::/126
keyring:
  left: 12345678901234567890123456789012
  right: 09876543210987654321098765432109
